### ISSUE TITLE
Feature request: Pin Note

### ISSUE THREAD

**Issue by Dizzap** [martinstoeckli/SilentNotes#121]
One feature that could come in handy - pinning a note.  
For example: I have a note that's a to do list, so I need to keep it at the top of everything. But every time I add a new note, it gets put at the top (or bottom, which I don't really like) so after a couple notes the to do list is buried and I have to constantly drag it to the top.    

I assume you store the position of the notes on the grid in some way, so this could work by simply rendering those first (like a "always on top" thing), or having a separate grid for pinned notes (see picture).  

Here's a simple drawing on how it could look:
![pin_note](https://user-images.githubusercontent.com/26771004/143691742-97777d36-09d6-4718-82e7-f0fbb541cffe.jpg)

It could be set either by a icon on the note:
![Untitled-1](https://user-images.githubusercontent.com/26771004/143694978-4878a332-5c3d-4464-bf9a-21d0f644e978.jpg)
or in the note's menu bar/menu: 
![Screenshot 2021-11-27 190425](https://user-images.githubusercontent.com/26771004/143691985-333eaf12-39c3-435f-a7e0-50ba61d0879c.png)
  
Let me know what you think.
Cheers,
Jakub

**Comment by martinstoeckli** [comment]
I like this idea and I would be pleased if you could implement it! My thoughs about it:

- I would not separate them on their own line, this is a bit of a waste of the precious space, especially on a tablet. It would be enough to keep the pinned notes before all other notes, maybe with a small icon indicating that it is pinned.
- There is no need for separate grids, the only thing we had to do is when inserting a new note, that we insert it after the last pinned note. And of course when it is pinned it has to go to the top. The question arises what happens when the user reorders a pinned note, but maybe we should rethink the orderring system anyway, it's not as comfortable as it could be...
- The idea to add the action to the notes context menu is brilliant, because it does not clutter the notes in the overview with even more icons (I was afraid of that).
