### ISSUE TITLE
Sync after pinning restores note's previous position

### ISSUE THREAD

**Issue by Dizzap** [martinstoeckli/SilentNotes#150]
If you sync right after pinning a note, it moves the note back to it's original position while keeping the pin status.
Steps to reproduce:

1. Create 4 notes and pin a 3 of them
2. Sync the repo with remote storage
3. Open note number 4 (unpinned), press the pin button, close the note and immediately sync the notes
4. The fourth note is now back at it's original place, instead of being at the first position, while still being displayed as pinned

*Windows

**Platform (please complete the following information):**
 - OS: Windows and Android

**Comment by Dizzap** [comment]
@martinstoeckli could you please test this and confirm if it's a general bug?

**Comment by Dizzap** [comment]
Drag&dropping the note to pin it does not cause this problem. Also d&d "fixes" the issue.

**Comment by Dizzap** [comment]
I'm thinking this is happening because the synchronization somehow happens before `NoteViewModel.RepositionNoteBecausePinStateChanged()` where the note is repositioned, so the original position is stored to the repo.

**Comment by martinstoeckli** [comment]
Can confirm the behaviour. In method RepositionNoteBecausePinStateChanged() the order should be marked as modified by calling noteRepository.RefreshOrderModifiedAt(), this call is missing. The call should be done only if the position really changed, because the latest order wins, it could unnecessarily overwrite an order change of another device otherwise.

**Comment by Dizzap** [comment]
Solved.

**Comment by martinstoeckli** [comment]
Just released a new version 6.1.1 and uploaded it to the stores.
