### ISSUE TITLE
Problems with WebDav synchronization

### ISSUE THREAD

**Issue by passanywhere** [martinstoeckli/SilentNotes#163]
Thank you so much for the app.
But I have a problem in using it. At first, I can sync properly on 1 PC and 1 Android phone through Webdav protocol.
But when I logged in on the second PC with the same WebDAV account, it didn't let me enter the transfer code, but generated a new transfer code after logging in. So, the second PC cannot sync with the previous PC and phone.

I tried logging out of my Webdav account on all 3 devices and generated a new Webdav login code
But when I logged in again, all 3 devices generated their own separate transfer codes by themselves. Even if I uninstall the app and reinstall it, it doesn't solve the problem.
Is there any solution to fix it? I tried to use WebDav service provided by two different WebDAV service providers, but I couldn't solve the problem.
Thanks!

**Comment by martinstoeckli** [comment]
Thank you for writing. So did I get it right that the repository can be uploaded/downloaded, but that it did not recognize the already uploaded repository? For me this sounds as the file listing doesn't work, probably because of an uncommon response by the server. Maybe the WebDav server was updated and changed its response, though you said you tried several providers?

In any case I would be very interested in testing this out. If it is possible for you, could you set up a new test directory for me and send me the credentials per email? Wifh such a directory I could check out what really happens.

**Comment by martinstoeckli** [comment]
Thanks to the access to your webdav directory, I could locate the problem and fix it, it will be part of the upcoming version 7.0 which is coming soon. The problem was indeed the interpretation of the "file listing" response, which is slightly different than the responses I saw so far. Thank you very much for creating a test directory!

**Comment by java-walker** [comment]
What should I do if I lose my transfer code?

**Comment by martinstoeckli** [comment]
@java-walker - You can show the transfer code any time as long as at least one device is connected to the online storage. If no installation exists anymore and you didn't save the transfercode, the repository of the online storage becomes useless and cannot be decrypted. The question is a bit too broad to give a helpful answer, please contact me directly if you need more information.
