### ISSUE TITLE
[Feature Request] Automatically parse URLs as clickable hyperlinks 

### ISSUE THREAD

**Issue by urmomsangus** [martinstoeckli/SilentNotes#183]
If a URL is pasted into the note, it is not clickable. You have to choose the three-dot menu at the top to create a hyperlink.

It would be awesome if there was an option to have the app automatically recognize properly formatted URLs and make them into hyperlinks.

Maybe even an option for a separate edit mode and a view mode?  That's is, if the note is in edit mode then the link is not clickable and you can edit it, whereas in view mode it would become a hyperlink.

**Comment by martinstoeckli** [comment]
This is actually how it works, when I copy a text containing a link from a website and then paste it to a note, it is preserved as a link. Even an url as text will be converted to a link on Windows, though it was kept as text on Android, I may have to investigate this difference.

You can already switch into the shopping mode to get a readonly note, in this mode a clicked link will immediately open the webpage instead of waiting for a second click.

**Comment by urmomsangus** [comment]
Oh, my apologies. 

When I was sharing a URL (see #182 ) then it does not become a hyperlink that is clickable.

You are correct that manually pasting a link will make it clickable.

I understand shopping mode you referenced.

So it appears my real issue involves 182  and that I can close this issue. Unless you want this issue open to address why sharing a URL to the app doesn't behave the same way on Android.

**Comment by urmomsangus** [comment]
Reopen, but close if needed. I discovered that on Android:

- long press to paste inside the note preserves the URL hyperlink
- using Gboard in-built paste from clipboard doesn't

**Comment by martinstoeckli** [comment]
There is indeed a difference between sharing and pasting, when recieving a shared text a new note is created, but there is no  editor running in this case. It is the editor which does the parsing and conversion to a link, and I'm not sure whether it could work without being visible in the GUI.
