### ISSUE TITLE
Cannot sync via unencrypted FTP

### ISSUE THREAD

**Issue by Gittyperson** [martinstoeckli/SilentNotes#75]
Thank you for your excellent SilentNotes. SFTP support would also be great!

Here's my issue. I first use the Windows version, and successfully synchronize a test note via FTP. A ~500 byte silentnotes file is created to the FTP server (enabling SSL does not work in my FTP case - it fails to connect).

I then go the Android version, and enter the same FTP data. It reports a successful sync. I was expecting it to ask for the transfer code, but it does not. I then check the file on the server, and it's become 0kb and obviously the Windows version now fails to sync ("could not read the notes from the server - invalid format").

**Comment by martinstoeckli** [comment]
I'm sorry you have problems with the synchronization. You are right that it should ask for the transfer code, it does it directly after downloading and before uploading. In this case there would be no upload at all from the Android device, because this step is omitted if there are no changes done on the device (to safe bandwidth).

So to me it sounds as if SilentNotes on the Android device downloaded an already corrupt file, this would also explain that no dialog was shown to enter the transfer code.

Is this reproducable, could you delete the repository from the FTP server and sync again from the Windows device? If it works, can you download the file manually and check if the file on the server is really intact? If so, maybe you could sync again with the Android device and check if the file on the server changed?

If you could do those tests it could help finding the problem, a reproducable situation makes trouble shooting much easier, thank you.

**Comment by Gittyperson** [comment]
Ok, thank you. I managed to get to transfer code prompt to appear, and after that it keeps working normally.

Tried it a few time and it seems it didn't like me creating the first note on Windows. Trying to sync with Android always modified the file into a 0kb one.

So, I deleted the file from the server again, created a note from Android this time, and then opened the Windows app which asked for the code.

**Comment by martinstoeckli** [comment]
Thank you for the information, I will check this out. It really sounds strange, because the code base is identical on both platforms, but testing never hurts and sometimes an odd behaviour points to a hidden problem.

**Comment by Gittyperson** [comment]
Sorry, I'm reopening this. Must be a few weeks that non-SLL FTP synchronization (same config as earlier messages) does not work:

"Could not connect to the server, please check the internet connection..."

Happens on both Windows and Android. Server and file are reachable and settings have not changed. Not sure if this started with one of the recent SilentNote updates. Can't think of something, nothing else changed on my end.

**Comment by martinstoeckli** [comment]
Just double checked, the last source change relevant to FTP is from 6.10.2020 and it just accepts anonymous access (blank username). Shortly after my last comment I also checked whether starting the repo on Windows causes any problems, as you described, but I could not reproduce this problem.

If you can create another FTP directory for me, on the same server with the same problems, then I would try to debug the issue. What do you think, is this possible for you?

**Comment by Gittyperson** [comment]
Thank you, I will try creating it. Note that I _am_ using username/password, just not SSL.

**Comment by martinstoeckli** [comment]
That's fine, if you could create the FTP directory, just send me username and password per e-mail ( available at https://www.martinstoeckli.ch/silentnotes ).

**Comment by Dizzap** [comment]
Hey, I'm also having troubles syncing using FTP. In my case it's the opposite - SSL. I'm able to connect using unencrypted FTP just fine using both Android and Windows clients. Should I create a separate issue for this or write the info here?

**Comment by martinstoeckli** [comment]
Hello @Dizzap , do you know whether you are using FTP over SSL or the SFTP (SSH) protocol? As far as I know, the DotNet framework only supports FTP over SSL. Otherwise I can offer the same, I will try to debug it, if you can setup such an FTP directory for me and send me username/password per email.

**Comment by Dizzap** [comment]
I have both SFTP and FTPS enabled just to be sure, former being on port 22 and latter on port 21. I'm not sure what format the URL is supposed to have but I tried specifying the port and the protocols in all the combinations.
I will enable unencrypted FTP for you to help with debugging. Login info is sent to your mail.

Thanks a lot.

**Comment by martinstoeckli** [comment]
@Dizzap thank you for setting up the FTP account. I could do some testing and found more than one problem, some of them will be fixed in the upcoming release 5.5.2. which is already uploaded to the store.

1. The DotNet framework only accepts the ftp:// prefix, but not ftps:// , the new version will therefore rewrite the url to an ftp:// version. This can be savely done, because SSL is not depending on the prefix, rather it will be activated when the option "Use secure connection (SSL)" is selected.
2. The SSL certificate could not be validated, this problem I solved in adding an option "Accept unsafe certificates". If this option is selected, all certificates are accepted even if they could not be validated.
3. It seems that the DotNet framework does not support "session reuse" which is required by some servers. This would require a third party library. Because the end-to-end encryption does not rely on a trusted server, I think it is better to recommend plain FTP instead.
4. As far as I know it is also not possible to establish a connection with SFTP (SSH connection).

**Comment by Gittyperson** [comment]
Ok, took me a while. I'm sorry but was unable to create a test folder/account for you.

Is there a safe way to attempt setting everything up again (sort of a 'reset') while keeping my current notes? I still have the silentnotes_repository.silentnotes file, it's syncing that stopped working. Thanks.

**Comment by martinstoeckli** [comment]
@Gittyperson - Yes as long as you have at least one local installation, you can safely delete the online repository and sync again. It is also possible to change to another online storage, SilentNotes will realize that it is the same repository.

**Comment by Gittyperson** [comment]
I'm closing this since I can't effectively troubleshoot it. Tried again but ran into the same problems. Switched to the Gdrive method and it's working smoothly. Security/privacy-wise, I'm assuming anything is probably better than unencrypted FTP anyway.

Thanks for your efforts.
